#!/usr/bin/env node
/**
 * Writes src/generated/tools.ts from openapi.json: the TOOLS table, one
 * `<Tool>Request` type alias per tool and the ToolMethods base class that
 * gives CrawlForge one typed method per tool. Also refreshes the generated
 * blocks in src/index.ts (type re-exports) and README.md (the tool table).
 *
 * Every number here comes from the spec: `credits` is `x-credits` and is
 * never typed by hand.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const spec = JSON.parse(readFileSync(new URL('openapi.json', root), 'utf8'));

const camel = (name) =>
  name.split('_').map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1))).join('');

const schemaName = (ref) => {
  const prefix = '#/components/schemas/';
  if (!ref.startsWith(prefix)) throw new Error(`Unexpected request schema ref ${ref}`);
  return ref.slice(prefix.length);
};

/**
 * Renders a cross-field rule (anyOf / oneOf / allOf of `required` lists and
 * `const` pins) as prose for a JSDoc line; anything richer falls back to JSON.
 */
const describeRule = (schema, top = true) => {
  const member = (m) => {
    const keys = Object.keys(m);
    if (keys.length === 1 && Array.isArray(m.required) && m.required.length === 1) return '`' + m.required[0] + '`';
    if (keys.length === 1 && m.properties) {
      const props = Object.entries(m.properties);
      if (props.length === 1) {
        const [name, rule] = props[0];
        if ('const' in rule) return '`' + name + '` = ' + JSON.stringify(rule.const);
        if (rule.not && 'const' in rule.not) return '`' + name + '` ≠ ' + JSON.stringify(rule.not.const);
      }
    }
    if (m.anyOf || m.oneOf || m.allOf) return describeRule(m, false);
    return JSON.stringify(m);
  };
  const wrap = (s) => (top ? s : `(${s})`);
  if (schema.oneOf) return wrap(`exactly one of ${schema.oneOf.map(member).join(', ')}`);
  if (schema.anyOf) return wrap(schema.anyOf.map(member).join(' or '));
  if (schema.allOf) return wrap(schema.allOf.map(member).join(' and '));
  return null;
};

const tools = Object.entries(spec.paths).map(([path, item]) => {
  const post = item.post;
  const name = path.replace(/^\/tools\//, '');
  if (post.operationId !== name) throw new Error(`operationId ${post.operationId} does not match path ${path}`);
  if (typeof post['x-credits'] !== 'number') throw new Error(`${name} has no numeric x-credits`);
  const request = schemaName(post.requestBody.content['application/json'].schema.$ref);
  const schema = spec.components.schemas[request];
  if (!schema) throw new Error(`${name}: schema ${request} missing`);
  return {
    name,
    method: camel(name),
    request,
    credits: post['x-credits'],
    creditsNote: post['x-credits-note'] ?? null,
    docsUrl: post['x-docs-url'],
    summary: post.summary,
    rule: describeRule(schema),
  };
});

const jsdoc = (lines) => ['/**', ...lines.map((l) => ` * ${l}`.trimEnd()), ' */'];
const q = (s) => JSON.stringify(s);
const safeComment = (s) => String(s).replace(/\*\//g, '* /');

const out = [];
out.push(
  '/**',
  ' * GENERATED by scripts/gen-tools.mjs from openapi.json. Do not edit; run',
  ' * `npm run generate`.',
  ' *',
  ' * ToolMethods is an abstract base class that CrawlForge extends, rather than',
  ' * an interface plus a runtime loop that patches the prototype. Both give',
  ' * full typing; the class needs one short body per tool but keeps every',
  ' * method a real declaration: "go to definition" lands here, the JSDoc',
  ' * (price, docs link, cross-field rule) shows on hover, and nothing runs at',
  ' * module load, which keeps `sideEffects: false` honest.',
  ' */',
  "import type { components } from './schema.js';",
  "import type { RequestOptions, ToolResult } from '../types.js';",
  '',
);

for (const t of tools) {
  out.push(`/** Request body for \`POST /tools/${t.name}\` (${t.method}). */`);
  out.push(`export type ${t.request} = components['schemas']['${t.request}'];`);
}
out.push('');

out.push('/** Every tool in the spec, in path order. `credits` is the base price (x-credits). */');
out.push('export const TOOLS = [');
for (const t of tools) {
  out.push('  {');
  out.push(`    name: ${q(t.name)},`);
  out.push(`    method: ${q(t.method)},`);
  out.push(`    credits: ${t.credits},`);
  out.push(`    creditsNote: ${t.creditsNote === null ? 'null' : q(t.creditsNote)},`);
  out.push(`    docsUrl: ${q(t.docsUrl)},`);
  out.push('  },');
}
out.push('] as const;', '');
out.push("export type ToolName = (typeof TOOLS)[number]['name'];");
out.push("export type ToolMethodName = (typeof TOOLS)[number]['method'];", '');

out.push('export abstract class ToolMethods {');
out.push('  /** Runs any tool by name; the typed methods below delegate to it. */');
out.push(
  '  abstract call<T = Record<string, unknown>>(tool: string, params: object, options?: RequestOptions): Promise<ToolResult<T>>;',
);
for (const t of tools) {
  const lines = [safeComment(t.summary), ''];
  lines.push(`Credits: ${t.credits}${t.creditsNote ? `; ${safeComment(t.creditsNote)}` : ''}.`);
  if (t.rule) lines.push(`Requires ${safeComment(t.rule)}; the API checks this, TypeScript cannot.`);
  lines.push(`@see ${t.docsUrl}`);
  out.push('');
  out.push(...jsdoc(lines).map((l) => `  ${l}`));
  out.push(`  ${t.method}(params: ${t.request}, options?: RequestOptions): Promise<ToolResult> {`);
  out.push(`    return this.call(${q(t.name)}, params, options);`);
  out.push('  }');
}
out.push('}', '');

writeFileSync(new URL('src/generated/tools.ts', root), out.join('\n'));

/** Replaces the text between two marker lines, keeping the markers. */
function replaceBlock(file, start, end, body) {
  const url = new URL(file, root);
  const text = readFileSync(url, 'utf8');
  const a = text.indexOf(start);
  const b = text.indexOf(end);
  if (a === -1 || b === -1 || b < a) throw new Error(`${file}: markers ${start} / ${end} not found`);
  const next = text.slice(0, a + start.length) + '\n' + body + '\n' + text.slice(b);
  if (next !== text) writeFileSync(url, next);
}

replaceBlock(
  'src/index.ts',
  '// generated:request-types:start',
  '// generated:request-types:end',
  ['export type {', ...tools.map((t) => `  ${t.request},`), "} from './generated/tools.js';"].join('\n'),
);

const table = [
  '| Method | Tool | Credits | Docs |',
  '|---|---|---|---|',
  ...tools.map(
    (t) =>
      `| \`${t.method}()\` | \`${t.name}\` | ${t.credits}${t.creditsNote ? `; ${t.creditsNote}` : ''} | [${t.name}](${t.docsUrl}) |`,
  ),
];
replaceBlock('README.md', '<!-- generated:tools:start -->', '<!-- generated:tools:end -->', table.join('\n'));

console.log(`tools.ts written (${tools.length} tools)`);
