#!/usr/bin/env node
/**
 * Writes src/generated/schema.d.ts from openapi.json with openapi-typescript.
 *
 * openapi.json is copied verbatim from the website and never edited here. The
 * document handed to openapi-typescript differs from it in exactly one way:
 * the top-level `anyOf` / `oneOf` / `allOf` on a `<Tool>Request` schema is
 * removed. Those keywords carry cross-field rules ("url or html", "query or
 * queries") whose members have no `properties`, and openapi-typescript renders
 * such a member as `unknown`. A union with `unknown` collapses to `unknown`,
 * which left seven request types with no properties at all. The types below
 * are therefore the `properties`-only view of each request body; the API
 * still validates the cross-field rule and answers 400 VALIDATION_ERROR when
 * it is broken. gen-tools.mjs prints the rule in each method's JSDoc.
 *
 * `defaultNonNullable` is off so that a property with a default stays
 * optional: these are input types, and the server fills the default.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const root = new URL('../', import.meta.url);
const spec = JSON.parse(readFileSync(new URL('openapi.json', root), 'utf8'));

const doc = structuredClone(spec);
const simplified = [];
for (const [name, schema] of Object.entries(doc.components.schemas)) {
  if (!name.endsWith('Request')) continue;
  for (const keyword of ['anyOf', 'oneOf', 'allOf']) {
    if (keyword in schema) {
      delete schema[keyword];
      if (!simplified.includes(name)) simplified.push(name);
    }
  }
}

const ast = await openapiTS(doc, { alphabetize: true, defaultNonNullable: false });

const header = [
  '/**',
  ' * GENERATED by scripts/gen-schema.mjs (openapi-typescript) from openapi.json.',
  ' * Do not edit; run `npm run generate`.',
  ' *',
  ' * Request types are the `properties`-only view of each request schema: the',
  ' * cross-field rule (anyOf / oneOf / allOf) was removed before generation on',
  ` * ${simplified.join(', ')}.`,
  ' * The API enforces those rules; see the method JSDoc in tools.ts.',
  ' */',
  '',
  '',
].join('\n');

const outDir = new URL('src/generated/', root);
mkdirSync(fileURLToPath(outDir), { recursive: true });
writeFileSync(new URL('schema.d.ts', outDir), header + astToString(ast));
console.log(`schema.d.ts written (${simplified.length} request schemas simplified)`);
